export default {
  login: 'MohamedHNoor',
  id: 97671133,
  node_id: 'U_kgDOBdJX3Q',
  avatar_url: 'https://avatars.githubusercontent.com/u/97671133?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/MohamedHNoor',
  html_url: 'https://github.com/MohamedHNoor',
  followers_url: 'https://api.github.com/users/MohamedHNoor/followers',
  following_url:
    'https://api.github.com/users/MohamedHNoor/following{/other_user}',
  gists_url: 'https://api.github.com/users/MohamedHNoor/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/MohamedHNoor/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/MohamedHNoor/subscriptions',
  organizations_url: 'https://api.github.com/users/MohamedHNoor/orgs',
  repos_url: 'https://api.github.com/users/MohamedHNoor/repos',
  events_url: 'https://api.github.com/users/MohamedHNoor/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/MohamedHNoor/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mohamed Hassan Noor',
  company: 'Software Developer',
  blog: 'https://mohamedhnoor.netlify.app',
  location: 'Cape Town South Africa',
  email: null,
  hireable: true,
  bio: 'Full-stack Developer | React | Redux | JavaScript | Ruby | Ruby on Rails | SQL | PostgreSQL | pair programming | remote work | Open to new job opportunities',
  twitter_username: 'MohamedHNoor',
  public_repos: 76,
  public_gists: 0,
  followers: 150,
  following: 217,
  created_at: '2022-01-13T10:56:33Z',
  updated_at: '2023-06-10T12:36:33Z',
};
